### ISSUE TITLE
WebSocket DISCONNECT /socket 

### ISSUE THREAD

**Issue by blitz156** [zerok/channels-in-docker#3]
Messages not showed in chat and server log:

> combinedserver_1  | [2017/03/07 06:32:37] WebSocket DISCONNECT /socket [172.25.0.1:33257]
> combinedserver_1  | [2017/03/07 06:32:39] WebSocket CONNECT /socket [172.25.0.1:33267]
> combinedserver_1  | [2017/03/07 06:32:45] WebSocket DISCONNECT /socket [172.25.0.1:33261]
> combinedserver_1  | [2017/03/07 06:32:53] WebSocket DISCONNECT /socket [172.25.0.1:33259]
> combinedserver_1  | [2017/03/07 06:32:55] WebSocket CONNECT /socket [172.25.0.1:33270]

Run command:

> docker-compose -f docker-compose.development.yml up

Production setup same result:

> interfaceserver_1  | 172.25.0.1:52051 - - [07/Mar/2017:06:39:25] "GET /" 200 2641
> interfaceserver_1  | 172.25.0.1:52057 - - [07/Mar/2017:06:39:25] "WSCONNECT /socket" - -
> interfaceserver_1  | 172.25.0.1:52049 - - [07/Mar/2017:06:39:28] "WSDISCONNECT /socket" - -
> interfaceserver_1  | 172.25.0.1:52043 - - [07/Mar/2017:06:39:28] "WSDISCONNECT /socket" - -
> interfaceserver_1  | 172.25.0.1:52059 - - [07/Mar/2017:06:39:31] "WSCONNECT /socket" - -
> interfaceserver_1  | 172.25.0.1:52053 - - [07/Mar/2017:06:39:36] "WSDISCONNECT /socket" - -
> interfaceserver_1  | 172.25.0.1:52055 - - [07/Mar/2017:06:39:36] "WSDISCONNECT /socket" - -

Chrome Version 56.0.2924.76 (64-bit)

**Comment by zerok** [comment]
Hi :)

Sorry the late response. Looks like somewhere an API changed. I've updated the example to work with the latest release :)

**Comment by blitz156** [comment]
Thanks :) :+1:
